server:
  servlet:
    context-path: /mipla2
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mipla?characterEncoding=UTF-8&serverTimezone=Asia/Tokyo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mipla
    password: mipla
  session:
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
      table-name: SPRING_SESSION
    sql:
      init:
        mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  spring-boot:
    run:
      jvmArguments:: -Xint
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    jp.vemi.mirel: DEBUG
mipla2:
  security:
    api:
      enabled: false
  config:
    storage-dir: "C:\\data\\m2\\storage"
